/**
 * Server-side error reporting for the Cloudflare Worker runtime.
 *
 * The Node/Cloudflare Sentry SDKs expect to wrap the whole worker export, which
 * this app cannot do (the entry is generated by TanStack Start + nitro). Instead
 * we post a minimal envelope directly to Sentry's ingest endpoint with `fetch`,
 * which is fully supported in workerd and adds no bundle weight.
 */
import { normalizeEnvironment } from "./env";

type ParsedDsn = {
  ingestUrl: string;
  publicKey: string;
};

let cachedDsn: ParsedDsn | null | undefined;

function parseDsn(): ParsedDsn | null {
  if (cachedDsn !== undefined) return cachedDsn;

  const raw = process.env["SENTRY_DSN"] ?? process.env["VITE_SENTRY_DSN"];
  if (!raw) {
    cachedDsn = null;
    return cachedDsn;
  }

  try {
    const url = new URL(raw);
    const projectId = url.pathname.replace(/^\//, "");
    if (!projectId || !url.username) {
      cachedDsn = null;
      return cachedDsn;
    }
    cachedDsn = {
      ingestUrl: `${url.protocol}//${url.host}/api/${projectId}/envelope/`,
      publicKey: url.username,
    };
  } catch {
    cachedDsn = null;
  }

  return cachedDsn;
}

function serializeError(error: unknown) {
  if (error instanceof Error) {
    return {
      type: error.name || "Error",
      value: error.message,
      stacktrace: error.stack ? { frames: parseStack(error.stack) } : undefined,
    };
  }
  return { type: "UnknownError", value: safeStringify(error) };
}

function safeStringify(value: unknown): string {
  if (typeof value === "string") return value;
  try {
    return JSON.stringify(value) ?? String(value);
  } catch {
    return String(value);
  }
}

/** Minimal V8 stack parser; frames are ordered oldest-first as Sentry expects. */
function parseStack(stack: string) {
  const frames = stack
    .split("\n")
    .slice(1)
    .map((line) => line.trim())
    .filter((line) => line.startsWith("at "))
    .map((line) => {
      const match = /^at\s+(?:(.*?)\s+\()?(.+?):(\d+):(\d+)\)?$/.exec(line);
      if (!match) return { function: line.replace(/^at\s+/, "") };
      return {
        function: match[1] || "<anonymous>",
        filename: match[2],
        lineno: Number(match[3]),
        colno: Number(match[4]),
        in_app: !match[2]?.includes("node_modules"),
      };
    });
  return frames.reverse();
}

export type ServerErrorContext = {
  request?: Request;
  tags?: Record<string, string>;
  extra?: Record<string, unknown>;
};

/**
 * Send an exception to Sentry. Never throws and never blocks the response path
 * beyond a single fetch; callers may ignore the returned promise.
 */
export async function captureServerException(
  error: unknown,
  context: ServerErrorContext = {},
): Promise<void> {
  const dsn = parseDsn();
  if (!dsn) return;

  const environment = normalizeEnvironment(
    process.env["APP_ENV"] ?? process.env["VITE_APP_ENV"],
  );
  const release = process.env["APP_RELEASE"] ?? process.env["VITE_APP_RELEASE"];
  const eventId = crypto.randomUUID().replace(/-/g, "");
  const sentAt = new Date().toISOString();

  const requestUrl = context.request ? new URL(context.request.url) : undefined;

  const event = {
    event_id: eventId,
    timestamp: Date.now() / 1000,
    platform: "javascript",
    level: "error",
    logger: "server",
    environment,
    ...(release ? { release } : {}),
    server_name: requestUrl?.host,
    tags: { runtime: "cloudflare-worker", ...context.tags },
    ...(context.extra ? { extra: context.extra } : {}),
    ...(context.request && requestUrl
      ? {
          request: {
            url: `${requestUrl.origin}${requestUrl.pathname}`,
            method: context.request.method,
            query_string: requestUrl.search.replace(/^\?/, ""),
          },
        }
      : {}),
    exception: { values: [serializeError(error)] },
  };

  const body = [
    JSON.stringify({ event_id: eventId, sent_at: sentAt }),
    JSON.stringify({ type: "event" }),
    JSON.stringify(event),
  ].join("\n");

  try {
    await fetch(dsn.ingestUrl, {
      method: "POST",
      headers: {
        "content-type": "application/x-sentry-envelope",
        "x-sentry-auth": `Sentry sentry_version=7, sentry_client=royeffect-worker/1.0, sentry_key=${dsn.publicKey}`,
      },
      body,
    });
  } catch {
    // Reporting must never break the request.
  }
}
